/* EFFETS1.H */

void zoom(int *img_src, int *img_dest, int x_src, int y_src, int x_src_img, int x_dest, int y_dest, int x_dest_img,int intens);
void zoom_tr(int *img_src, int *img_dest, int x_src, int y_src, int x_src_img, int x_dest, int y_dest, int x_dest_img, int col_tran, int toler, int intens);
void motif(int *img_src, int *img_dest, int x_src, int y_src, int x_src_img, int x_dest, int y_dest, int x_dest_img);
void fill(int *img_dest, int x_dest, int y_dest, int x_dest_img, int coul);
