/* Indice du ressource pour MOUNTAIN */

#define LEMENU   0   /* Arbre menu */
#define MN_INFO  10  /* STRING dans l'arbre LEMENU */
#define MN_NEW   19  /* STRING dans l'arbre LEMENU */
#define MN_LOAD  21  /* STRING dans l'arbre LEMENU */
#define MN_SAV   22  /* STRING dans l'arbre LEMENU */
#define MN_SAV_COM 23  /* STRING dans l'arbre LEMENU */
#define MN_IMP_FLH 25  /* STRING dans l'arbre LEMENU */
#define MN_IMP_FLI 26  /* STRING dans l'arbre LEMENU */
#define MN_IMP_RIM 27  /* STRING dans l'arbre LEMENU */
#define MN_IMP_SUIT 28  /* STRING dans l'arbre LEMENU */
#define MN_EXP_MOD 30  /* STRING dans l'arbre LEMENU */
#define MN_EXP_MPL 31  /* STRING dans l'arbre LEMENU */
#define MN_INFO_MDI 33  /* STRING dans l'arbre LEMENU */
#define MN_QUIT  35  /* STRING dans l'arbre LEMENU */
#define MN_OBJ   37  /* STRING dans l'arbre LEMENU */
#define MN_PISTES 38  /* STRING dans l'arbre LEMENU */
#define MN_PROJET 39  /* STRING dans l'arbre LEMENU */
#define MN_TRAN  40  /* STRING dans l'arbre LEMENU */
#define MN_ZINF  41  /* STRING dans l'arbre LEMENU */
#define MN_INFO_OPT 43  /* STRING dans l'arbre LEMENU */
#define MN_VISU  44  /* STRING dans l'arbre LEMENU */
#define MN_TRANSP 45  /* STRING dans l'arbre LEMENU */
#define MN_DEP   46  /* STRING dans l'arbre LEMENU */
#define MN_INT   47  /* STRING dans l'arbre LEMENU */
#define MN_EFF   48  /* STRING dans l'arbre LEMENU */
#define MN_ANI1  51  /* STRING dans l'arbre LEMENU */
#define MN_EFF1  52  /* STRING dans l'arbre LEMENU */
#define MN_COUPL 53  /* STRING dans l'arbre LEMENU */
#define MN_ANI2  54  /* STRING dans l'arbre LEMENU */
#define MN_EFF2  55  /* STRING dans l'arbre LEMENU */
#define MN_GENE  56  /* STRING dans l'arbre LEMENU */
#define MN_SUPA  58  /* STRING dans l'arbre LEMENU */
#define MN_SUPB  59  /* STRING dans l'arbre LEMENU */
#define MN_SUPG  60  /* STRING dans l'arbre LEMENU */
#define MN_SUPPR_PI 62  /* STRING dans l'arbre LEMENU */
#define MN_PRJFORMAT 64  /* STRING dans l'arbre LEMENU */
#define MN_PRJFON 65  /* STRING dans l'arbre LEMENU */
#define MN_CHM   67  /* STRING dans l'arbre LEMENU */
#define MN_OPTVISU 68  /* STRING dans l'arbre LEMENU */
#define MN_OPTGENE 69  /* STRING dans l'arbre LEMENU */
#define MN_OPTPISTES 70  /* STRING dans l'arbre LEMENU */
#define MN_OPTPREV 71  /* STRING dans l'arbre LEMENU */
#define MN_CARTE 72  /* STRING dans l'arbre LEMENU */
#define MN_SMPTE 74  /* STRING dans l'arbre LEMENU */
#define MN_MEM   75  /* STRING dans l'arbre LEMENU */
#define MN_SAVOPT 77  /* STRING dans l'arbre LEMENU */

#define CONTROL  1   /* Formulaire/Dialogue */
#define V_PLAY   1   /* USERDEF dans l'arbre CONTROL */
#define V_BACK   2   /* USERDEF dans l'arbre CONTROL */
#define V_STOP   3   /* USERDEF dans l'arbre CONTROL */
#define V_FON    4   /* BOX dans l'arbre CONTROL */
#define V_BAR    5   /* BOX dans l'arbre CONTROL */
#define V_FORW   6   /* USERDEF dans l'arbre CONTROL */
#define V_IN     7   /* USERDEF dans l'arbre CONTROL */
#define V_OUT    8   /* USERDEF dans l'arbre CONTROL */

#define CONTROL1 2   /* Formulaire/Dialogue */

#define BINFO    3   /* Formulaire/Dialogue */
#define INFO_MEM 1   /* TEXT dans l'arbre BINFO */
#define BINFO_REG 3   /* TEXT dans l'arbre BINFO */
#define BINFO_BGREETS 4   /* BUTTON dans l'arbre BINFO */
#define BINFO_BLAUT 14  /* BUTTON dans l'arbre BINFO */
#define BINFO_GREETS 23  /* BOXTEXT dans l'arbre BINFO */
#define BINFO_LAUT 24  /* BOXTEXT dans l'arbre BINFO */
#define INFO_VER 31  /* STRING dans l'arbre BINFO */

#define KEY_FRAME 4   /* Formulaire/Dialogue */
#define KEY_ANI_IMP 3   /* TEXT dans l'arbre KEY_FRAME */
#define KEY_KEY  5   /* TEXT dans l'arbre KEY_FRAME */
#define KEY_IMG  6   /* BOXTEXT dans l'arbre KEY_FRAME */
#define KEY_DESC 7   /* TEXT dans l'arbre KEY_FRAME */
#define KEY_FREQ 9   /* TEXT dans l'arbre KEY_FRAME */

#define OPT_ANIM 5   /* Formulaire/Dialogue */
#define OPTA_POSO 1   /* FTEXT dans l'arbre OPT_ANIM */
#define OPTA_POSA 2   /* STRING dans l'arbre OPT_ANIM */
#define OPTA_PISTE 3   /* STRING dans l'arbre OPT_ANIM */
#define OPTA_TRAN 4   /* STRING dans l'arbre OPT_ANIM */
#define OPTA_ONCE 6   /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_BOUCL 7   /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_PING 8   /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_TIMESPLINE 12  /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_TEX_SPLINE 13  /* TEXT dans l'arbre OPT_ANIM */
#define OPTA_OK  14  /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_AN  15  /* BUTTON dans l'arbre OPT_ANIM */
#define OPTA_POSO_OUT 16  /* FTEXT dans l'arbre OPT_ANIM */

#define CHOIX    6   /* Formulaire/Dialogue */
#define TXT1     1   /* TEXT dans l'arbre CHOIX */
#define CUP      11  /* BOXCHAR dans l'arbre CHOIX */
#define CFON     12  /* BOX dans l'arbre CHOIX */
#define CASS     13  /* BOXCHAR dans l'arbre CHOIX */
#define CDOWN    14  /* BOXCHAR dans l'arbre CHOIX */

#define NEW_PRJ  7   /* Formulaire/Dialogue */
#define NEW_TITRE 1   /* TEXT dans l'arbre NEW_PRJ */
#define NEW_NAME 2   /* FTEXT dans l'arbre NEW_PRJ */
#define NEW_X    4   /* FTEXT dans l'arbre NEW_PRJ */
#define NEW_Y    5   /* FTEXT dans l'arbre NEW_PRJ */
#define NEW_LONG 8   /* FTEXT dans l'arbre NEW_PRJ */
#define NEW_RED  10  /* BOXTEXT dans l'arbre NEW_PRJ */
#define NEW_SPEED 12  /* BUTTON dans l'arbre NEW_PRJ */
#define NEW_OK   14  /* BUTTON dans l'arbre NEW_PRJ */
#define NEW_ANN  15  /* BUTTON dans l'arbre NEW_PRJ */
#define NEW_POP_PRE 17  /* BUTTON dans l'arbre NEW_PRJ */

#define POP_SPEED 8   /* Formulaire/Dialogue */

#define COULEUR  9   /* Formulaire/Dialogue */
#define COUL_OK  1   /* BUTTON dans l'arbre COULEUR */
#define COUL_ANN 2   /* BUTTON dans l'arbre COULEUR */
#define COUL_FONR 3   /* BOX dans l'arbre COULEUR */
#define COUL_ASSR 4   /* BOXTEXT dans l'arbre COULEUR */
#define COUL_UPR 5   /* BOXCHAR dans l'arbre COULEUR */
#define COUL_DWR 6   /* BOXCHAR dans l'arbre COULEUR */
#define COUL_FONV 7   /* BOX dans l'arbre COULEUR */
#define COUL_ASSV 8   /* BOXTEXT dans l'arbre COULEUR */
#define COUL_UPV 9   /* BOXCHAR dans l'arbre COULEUR */
#define COUL_DWV 10  /* BOXCHAR dans l'arbre COULEUR */
#define COUL_FONB 11  /* BOX dans l'arbre COULEUR */
#define COUL_ASSB 12  /* BOXTEXT dans l'arbre COULEUR */
#define COUL_UPB 13  /* BOXCHAR dans l'arbre COULEUR */
#define COUL_DWB 14  /* BOXCHAR dans l'arbre COULEUR */
#define COUL_TR  15  /* FTEXT dans l'arbre COULEUR */
#define COUL_TV  16  /* FTEXT dans l'arbre COULEUR */
#define COUL_TB  17  /* FTEXT dans l'arbre COULEUR */
#define COUL_TST 18  /* BOX dans l'arbre COULEUR */
#define COUL_TSTB 19  /* BUTTON dans l'arbre COULEUR */

#define IMPORT_FLH 10  /* Formulaire/Dialogue */
#define IFLH_OK  2   /* BUTTON dans l'arbre IMPORT_FLH */
#define IFLH_ANN 3   /* BUTTON dans l'arbre IMPORT_FLH */
#define IFLH_CHM 5   /* TEXT dans l'arbre IMPORT_FLH */
#define IFLH_DESC 6   /* TEXT dans l'arbre IMPORT_FLH */
#define IFLH_KEY 11  /* TEXT dans l'arbre IMPORT_FLH */
#define IFLH_FREQ 13  /* BUTTON dans l'arbre IMPORT_FLH */

#define POP_KEY  11  /* Formulaire/Dialogue */

#define OPT_OBJET 12  /* Formulaire/Dialogue */
#define OPTO_NOM 1   /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_TYPE 2   /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_DESC 3   /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_IN  5   /* FTEXT dans l'arbre OPT_OBJET */
#define OPTO_OUT 6   /* FTEXT dans l'arbre OPT_OBJET */
#define OPTO_CHM 9   /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_FKEY 10  /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_KEY 11  /* TEXT dans l'arbre OPT_OBJET */
#define OPTO_IPRE 12  /* FTEXT dans l'arbre OPT_OBJET */
#define OPTO_OK  13  /* BUTTON dans l'arbre OPT_OBJET */
#define OPTO_ANN 14  /* BUTTON dans l'arbre OPT_OBJET */

#define POP_OBJET 13  /* Formulaire/Dialogue */
#define POBJ_INFO 1   /* STRING dans l'arbre POP_OBJET */
#define POBJ_EFF 2   /* STRING dans l'arbre POP_OBJET */
#define POBJ_VISU 3   /* STRING dans l'arbre POP_OBJET */
#define POBJ_VEXT 4   /* STRING dans l'arbre POP_OBJET */

#define OPT_CHM  14  /* Formulaire/Dialogue */
#define OPT_OK   1   /* BUTTON dans l'arbre OPT_CHM */
#define OPT_ANN  2   /* BUTTON dans l'arbre OPT_CHM */
#define OPT_KEY  7   /* BOXTEXT dans l'arbre OPT_CHM */
#define OPT_VEXT 8   /* BOXTEXT dans l'arbre OPT_CHM */
#define OPT_VIEXT 9   /* BOXTEXT dans l'arbre OPT_CHM */
#define OPT_IMP  10  /* BOXTEXT dans l'arbre OPT_CHM */
#define OPT_MPL  12  /* BOXTEXT dans l'arbre OPT_CHM */

#define OPT_VISU 15  /* Formulaire/Dialogue */
#define OPTV_OK  1   /* BUTTON dans l'arbre OPT_VISU */
#define OPTV_ANN 2   /* BUTTON dans l'arbre OPT_VISU */
#define OV_HG    4   /* USERDEF dans l'arbre OPT_VISU */
#define OV_HC    5   /* USERDEF dans l'arbre OPT_VISU */
#define OV_HD    6   /* USERDEF dans l'arbre OPT_VISU */
#define OV_CG    7   /* USERDEF dans l'arbre OPT_VISU */
#define OV_CC    8   /* USERDEF dans l'arbre OPT_VISU */
#define OV_CD    9   /* USERDEF dans l'arbre OPT_VISU */
#define OV_BG    10  /* USERDEF dans l'arbre OPT_VISU */
#define OV_BC    11  /* USERDEF dans l'arbre OPT_VISU */
#define OV_BD    12  /* USERDEF dans l'arbre OPT_VISU */
#define OV_LAST  13  /* BUTTON dans l'arbre OPT_VISU */
#define OPTV_INFO 14  /* BUTTON dans l'arbre OPT_VISU */
#define OPTV_FAST 15  /* BUTTON dans l'arbre OPT_VISU */
#define OPTV_BOUCLE 16  /* BUTTON dans l'arbre OPT_VISU */

#define IMG_FON  16  /* Formulaire/Dialogue */
#define FON_COUL 1   /* BUTTON dans l'arbre IMG_FON */
#define FON_MOT  3   /* BUTTON dans l'arbre IMG_FON */
#define FON_ZOM  4   /* BUTTON dans l'arbre IMG_FON */
#define FON_OBJ  5   /* BUTTON dans l'arbre IMG_FON */
#define FON_NOM_OBJ 6   /* BUTTON dans l'arbre IMG_FON */
#define FON_SET_COUL 7   /* BUTTON dans l'arbre IMG_FON */
#define FON_OK   8   /* BUTTON dans l'arbre IMG_FON */
#define FON_ANN  9   /* BUTTON dans l'arbre IMG_FON */

#define OPT_GENE 17  /* Formulaire/Dialogue */
#define OPTG_OK  1   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_ANN 2   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_NVDI 3   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_REL 4   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_FPRJ 6   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_FPIST 7   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_FOBJ 8   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_FTRAN 9   /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_POP_T 12  /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_TAILLE 13  /* FTEXT dans l'arbre OPT_GENE */
#define OPTG_ALRT 14  /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_POP_B 15  /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_C_LDG 16  /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_LDG8 17  /* BUTTON dans l'arbre OPT_GENE */
#define OPTG_ROUND 18  /* BUTTON dans l'arbre OPT_GENE */

#define OPT_PISTE 18  /* Formulaire/Dialogue */
#define OPTP_A1  3   /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_A2  7   /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_A3  9   /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_BUF 10  /* FTEXT dans l'arbre OPT_PISTE */
#define OPTP_OK  12  /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_ANN 13  /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_PROP 14  /* BUTTON dans l'arbre OPT_PISTE */
#define OPTP_AFF_INT 15  /* BUTTON dans l'arbre OPT_PISTE */

#define MOUVEMENT 19  /* Formulaire/Dialogue */
#define MOU_OK   1   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_ANN  2   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_LOAD 3   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_SAVE 4   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_CENTRE 5   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_FILL 6   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_ENLEVE 7   /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_PRE  8   /* BOX dans l'arbre MOUVEMENT */
#define MOU_MOU  9   /* BOX dans l'arbre MOUVEMENT */
#define MOU_FON_R 10  /* BOX dans l'arbre MOUVEMENT */
#define MOU_ASS_R 11  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_R_M  12  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_R_P  13  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_FON_X 14  /* BOX dans l'arbre MOUVEMENT */
#define MOU_ASS_X 15  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_X_M  16  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_X_P  17  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_FON_Y 18  /* BOX dans l'arbre MOUVEMENT */
#define MOU_ASS_Y 19  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_Y_M  20  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_Y_P  21  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_FON_TEMPS 25  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_TEMPS 26  /* BOX dans l'arbre MOUVEMENT */
#define MOU_NUM_PT 28  /* TEXT dans l'arbre MOUVEMENT */
#define MOU_TSPLINE 29  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_PT_PCENT 30  /* TEXT dans l'arbre MOUVEMENT */
#define MOU_NB_IMG 31  /* FTEXT dans l'arbre MOUVEMENT */
#define MOU_FOND_COL 32  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_TRAN 33  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_COUL 34  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_PICK 35  /* BOX dans l'arbre MOUVEMENT */
#define MOU_R    36  /* FTEXT dans l'arbre MOUVEMENT */
#define MOU_V    37  /* FTEXT dans l'arbre MOUVEMENT */
#define MOU_B    38  /* FTEXT dans l'arbre MOUVEMENT */
#define MOU_PRE_COUL 39  /* BOX dans l'arbre MOUVEMENT */
#define MOU_SUP_MVT 45  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_FON_PX 46  /* BOX dans l'arbre MOUVEMENT */
#define MOU_ASS_PX 47  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_PX_M 48  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_PX_P 49  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_FON_PY 50  /* BOX dans l'arbre MOUVEMENT */
#define MOU_ASS_PY 51  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_PY_M 52  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_PY_P 53  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_TREL 56  /* BUTTON dans l'arbre MOUVEMENT */
#define MOU_ANIM 57  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_MAJ  58  /* BOXTEXT dans l'arbre MOUVEMENT */
#define MOU_NEW_PT 59  /* BUTTON dans l'arbre MOUVEMENT */

#define CARTE    20  /* Formulaire/Dialogue */
#define CARTE_FAL 2   /* BUTTON dans l'arbre CARTE */
#define CARTE_NOVA 3   /* BUTTON dans l'arbre CARTE */
#define CARTE_TRUE_RVB 7   /* BUTTON dans l'arbre CARTE */
#define CARTE_16_COUL 9   /* BUTTON dans l'arbre CARTE */
#define CARTE_LDG 11  /* BUTTON dans l'arbre CARTE */
#define CARTE_FORCE_VDI 12  /* BUTTON dans l'arbre CARTE */
#define CARTE_OK 13  /* BUTTON dans l'arbre CARTE */
#define CARTE_ANN 14  /* BUTTON dans l'arbre CARTE */

#define POP_OBJ_PRJ 21  /* Formulaire/Dialogue */
#define PPRJ_EFF 1   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_VIS 2   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_MOU 3   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_FX  4   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_TRAN 5   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_OPT 6   /* STRING dans l'arbre POP_OBJ_PRJ */
#define PPRJ_INT 7   /* STRING dans l'arbre POP_OBJ_PRJ */

#define MOD_IMP  22  /* Formulaire/Dialogue */
#define MDI_NB_MOD 2   /* TEXT dans l'arbre MOD_IMP */
#define MDI_PREV 3   /* BUTTON dans l'arbre MOD_IMP */
#define MDI_N_MOD 4   /* BOXTEXT dans l'arbre MOD_IMP */
#define MDI_NEXT 5   /* BUTTON dans l'arbre MOD_IMP */
#define MDI_FON  6   /* BUTTON dans l'arbre MOD_IMP */
#define MDI_DESC 7   /* TEXT dans l'arbre MOD_IMP */
#define MDI_ID   10  /* TEXT dans l'arbre MOD_IMP */
#define MDI_VER  11  /* TEXT dans l'arbre MOD_IMP */
#define MDI_BUFF 13  /* TEXT dans l'arbre MOD_IMP */
#define MDI_FIC_NAME 15  /* TEXT dans l'arbre MOD_IMP */
#define MDI_IMP  18  /* BUTTON dans l'arbre MOD_IMP */
#define MDI_EXP  19  /* BUTTON dans l'arbre MOD_IMP */

#define ICONE    23  /* Formulaire/Dialogue */

#define MEMORY   24  /* Formulaire/Dialogue */
#define MEM_FON  1   /* BOX dans l'arbre MEMORY */
#define MEM_ASS  2   /* BOX dans l'arbre MEMORY */
#define MEM_TXT  3   /* TEXT dans l'arbre MEMORY */

#define TRANSPARENCE 25  /* Formulaire/Dialogue */
#define TRAN_OK  1   /* BUTTON dans l'arbre TRANSPARENCE */
#define TRAN_AN  2   /* BUTTON dans l'arbre TRANSPARENCE */
#define TRAN_PREV 3   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_BLANC 5   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_NOIR 6   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_ROUGE 7   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_GRIS 8   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_VERT 9   /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_GRISF 10  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_BLUE 11  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_CYAN 12  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_COUL 13  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_PICK 14  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_R   15  /* FTEXT dans l'arbre TRANSPARENCE */
#define TRAN_V   16  /* FTEXT dans l'arbre TRANSPARENCE */
#define TRAN_B   17  /* FTEXT dans l'arbre TRANSPARENCE */
#define TRAN_FON 19  /* BOX dans l'arbre TRANSPARENCE */
#define TRAN_ASS 20  /* BOXTEXT dans l'arbre TRANSPARENCE */
#define TRAN_REEL 21  /* BUTTON dans l'arbre TRANSPARENCE */
#define TRAN_SUPR 22  /* BUTTON dans l'arbre TRANSPARENCE */
#define TRAN_MAJ 23  /* BOXTEXT dans l'arbre TRANSPARENCE */
#define TRAN_IMG_USED 24  /* FTEXT dans l'arbre TRANSPARENCE */

#define CALC_FIN 26  /* Formulaire/Dialogue */
#define CALC_CONF 1   /* BUTTON dans l'arbre CALC_FIN */
#define CALC_TOUT 3   /* BUTTON dans l'arbre CALC_FIN */
#define CALC_ONLY 4   /* BUTTON dans l'arbre CALC_FIN */
#define CALC_DE  5   /* FTEXT dans l'arbre CALC_FIN */
#define CALC_A   6   /* FTEXT dans l'arbre CALC_FIN */
#define CALC_NB  7   /* STRING dans l'arbre CALC_FIN */
#define CALC_FIC 9   /* BOXTEXT dans l'arbre CALC_FIN */
#define CALC_EXP 11  /* BUTTON dans l'arbre CALC_FIN */
#define CALC_GO  12  /* BUTTON dans l'arbre CALC_FIN */
#define CALC_FON 13  /* BOX dans l'arbre CALC_FIN */
#define CALC_BAR 14  /* BOX dans l'arbre CALC_FIN */
#define CALC_PREV 16  /* BOX dans l'arbre CALC_FIN */
#define CALC_AFF 17  /* BUTTON dans l'arbre CALC_FIN */

#define CALC_MPLAYER 27  /* Formulaire/Dialogue */
#define MPL_TOUT 2   /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_ONLY 3   /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_DE   4   /* FTEXT dans l'arbre CALC_MPLAYER */
#define MPL_A    5   /* FTEXT dans l'arbre CALC_MPLAYER */
#define MPL_NB   6   /* STRING dans l'arbre CALC_MPLAYER */
#define MPL_FIC  8   /* BOXTEXT dans l'arbre CALC_MPLAYER */
#define MPL_GO   9   /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_FON  10  /* BOX dans l'arbre CALC_MPLAYER */
#define MPL_BAR  11  /* BOX dans l'arbre CALC_MPLAYER */
#define MPL_PREV 12  /* BOX dans l'arbre CALC_MPLAYER */
#define MPL_AFF  13  /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_SON  15  /* BOXTEXT dans l'arbre CALC_MPLAYER */
#define MPL_FORMAT 16  /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_KEY  19  /* BUTTON dans l'arbre CALC_MPLAYER */
#define MPL_MPL  20  /* TEXT dans l'arbre CALC_MPLAYER */
#define MPL_POP_Q 22  /* BUTTON dans l'arbre CALC_MPLAYER */

#define POP_MPL_KEY 28  /* Formulaire/Dialogue */

#define POP_SIZ_PRE 29  /* Formulaire/Dialogue */

#define INTENSITE 30  /* Formulaire/Dialogue */
#define INT_CTE  1   /* BUTTON dans l'arbre INTENSITE */
#define INT_VARI 2   /* BUTTON dans l'arbre INTENSITE */
#define INT_0P   4   /* BUTTON dans l'arbre INTENSITE */
#define INT_25P  5   /* BUTTON dans l'arbre INTENSITE */
#define INT_50P  6   /* BUTTON dans l'arbre INTENSITE */
#define INT_75P  7   /* BUTTON dans l'arbre INTENSITE */
#define INT_100P 8   /* BUTTON dans l'arbre INTENSITE */
#define INT_TIME 12  /* BUTTON dans l'arbre INTENSITE */
#define INT_T_TEXT 13  /* TEXT dans l'arbre INTENSITE */
#define INT_OK   14  /* BUTTON dans l'arbre INTENSITE */
#define INT_ANN  15  /* BUTTON dans l'arbre INTENSITE */

#define ZINFO    31  /* Formulaire/Dialogue */
#define ZIN_POPZ 1   /* BUTTON dans l'arbre ZINFO */
#define ZIN_CUR  4   /* TEXT dans l'arbre ZINFO */

#define POP_ZOOM 32  /* Formulaire/Dialogue */

#define POP_FORMAT 33  /* Formulaire/Dialogue */

#define POP_QUALITE 34  /* Formulaire/Dialogue */

#define ALERT    35  /* Formulaire/Dialogue */
#define POINT    1   /* USERDEF dans l'arbre ALERT */
#define INTERRO  2   /* USERDEF dans l'arbre ALERT */
#define STOP     3   /* USERDEF dans l'arbre ALERT */
#define ALRT1    4   /* STRING dans l'arbre ALERT */
#define ALB1     9   /* BUTTON dans l'arbre ALERT */

#define SUITE_IMG 36  /* Formulaire/Dialogue */
#define SUIT_FIC 2   /* BOXTEXT dans l'arbre SUITE_IMG */
#define SUIT_NB_IMG 3   /* TEXT dans l'arbre SUITE_IMG */
#define SUITE_DESC 4   /* TEXT dans l'arbre SUITE_IMG */
#define SUIT_MOD 5   /* TEXT dans l'arbre SUITE_IMG */
#define SUIT_FON_TRI 7   /* BOX dans l'arbre SUITE_IMG */
#define SUITE_DEBUT 8   /* FTEXT dans l'arbre SUITE_IMG */
#define SUIT_NB  9   /* FTEXT dans l'arbre SUITE_IMG */
#define SUIT_FLECHES 10  /* IMAGE dans l'arbre SUITE_IMG */
#define SUIT_TXT_TRI 11  /* STRING dans l'arbre SUITE_IMG */
#define SUIT_TRI 12  /* BUTTON dans l'arbre SUITE_IMG */
#define SUIT_FON_ZEROS 13  /* BOX dans l'arbre SUITE_IMG */
#define SUIT_ZEROS 14  /* FTEXT dans l'arbre SUITE_IMG */
#define SUIT_MODE_CHM 15  /* BUTTON dans l'arbre SUITE_IMG */
#define SUIT_NUM 20  /* FTEXT dans l'arbre SUITE_IMG */
#define SUIT_OK  21  /* BUTTON dans l'arbre SUITE_IMG */
#define SUIT_ANN 22  /* BUTTON dans l'arbre SUITE_IMG */

#define POP_RCH  37  /* Formulaire/Dialogue */

#define POP_TRI  38  /* Formulaire/Dialogue */

#define OPT_APRV 39  /* Formulaire/Dialogue */
#define APRV_OK  1   /* BUTTON dans l'arbre OPT_APRV */
#define APRV_ANN 2   /* BUTTON dans l'arbre OPT_APRV */
#define APRV_TREEL 4   /* BUTTON dans l'arbre OPT_APRV */
#define APRV_PREC 5   /* BUTTON dans l'arbre OPT_APRV */
#define APRV_PREEM 6   /* BUTTON dans l'arbre OPT_APRV */
#define APRV_CURS 9   /* BUTTON dans l'arbre OPT_APRV */

#define CHX_TIME 40  /* Formulaire/Dialogue */
#define CTIM_OK  1   /* BUTTON dans l'arbre CHX_TIME */
#define CTIM_ANN 2   /* BUTTON dans l'arbre CHX_TIME */
#define CTIM_FON 3   /* BOX dans l'arbre CHX_TIME */
#define CTIM_ASS 4   /* BOXCHAR dans l'arbre CHX_TIME */
#define CTIM_UP  5   /* BOXCHAR dans l'arbre CHX_TIME */
#define CTIM_DOWN 6   /* BOXCHAR dans l'arbre CHX_TIME */
#define CTIM_PREM 8   /* TEXT dans l'arbre CHX_TIME */
#define CTIM_NEW 20  /* BUTTON dans l'arbre CHX_TIME */
#define CTIME_EFF 21  /* BUTTON dans l'arbre CHX_TIME */
#define CTIM_LOAD 22  /* BUTTON dans l'arbre CHX_TIME */
#define CTIM_SAV 23  /* BUTTON dans l'arbre CHX_TIME */
#define CTIM_PREV 24  /* BOX dans l'arbre CHX_TIME */
#define CTIM_EDIT 26  /* BUTTON dans l'arbre CHX_TIME */

#define TIME_EDIT 41  /* Formulaire/Dialogue */
#define ETIM_OK  1   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_ANN 2   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_MAIN 3   /* BOX dans l'arbre TIME_EDIT */
#define ETIM_LOAD 4   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_SAVE 5   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_RESET 6   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_NAME 7   /* FTEXT dans l'arbre TIME_EDIT */
#define ETIM_MODE 8   /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_POS 10  /* BOXTEXT dans l'arbre TIME_EDIT */
#define ETIM_INTER 12  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_SMOOTH1 13  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_SMOOTH2 15  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_SMOOTH3 16  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_LIMITES 17  /* BOX dans l'arbre TIME_EDIT */
#define ETIM_1PT 18  /* TEXT dans l'arbre TIME_EDIT */
#define ETIM_2PT 19  /* TEXT dans l'arbre TIME_EDIT */
#define ETIM_FNC 20  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_EFF 21  /* BUTTON dans l'arbre TIME_EDIT */
#define ETIM_ANNO 23  /* IMAGE dans l'arbre TIME_EDIT */

#define POP_TIME_MODE 42  /* Formulaire/Dialogue */

#define PTIME    43  /* Formulaire/Dialogue */
#define PTIM_OK  1   /* BUTTON dans l'arbre PTIME */
#define PTIM_ANN 2   /* BUTTON dans l'arbre PTIME */
#define PTIM_TITRE 3   /* TEXT dans l'arbre PTIME */
#define PTIM_NOM1 4   /* TEXT dans l'arbre PTIME */
#define PTIM_VAL1 5   /* FTEXT dans l'arbre PTIME */
#define PTIM_NOM2 6   /* TEXT dans l'arbre PTIME */
#define PTIM_NOM3 7   /* TEXT dans l'arbre PTIME */
#define PTIM_VAL2 8   /* FTEXT dans l'arbre PTIME */
#define PTIM_VAL3 9   /* FTEXT dans l'arbre PTIME */
#define PTIM_NOM4 10  /* TEXT dans l'arbre PTIME */
#define PTIM_VAL4 11  /* FTEXT dans l'arbre PTIME */

#define FONCTIONS 44  /* Formulaire/Dialogue */

#define TIM_EFFET 45  /* Formulaire/Dialogue */

#define POP_TRANSIT 46  /* Formulaire/Dialogue */
#define PTRS_PARA 1   /* STRING dans l'arbre POP_TRANSIT */
#define PTRS_EFF 2   /* STRING dans l'arbre POP_TRANSIT */
#define PTRS_INFO 3   /* STRING dans l'arbre POP_TRANSIT */

#define TRAN_INFO 47  /* Formulaire/Dialogue */
#define TRSI_OK  1   /* BUTTON dans l'arbre TRAN_INFO */
#define TRSI_ANN 2   /* BUTTON dans l'arbre TRAN_INFO */
#define TRSI_NOM 3   /* TEXT dans l'arbre TRAN_INFO */
#define TRSI_DEP 4   /* FTEXT dans l'arbre TRAN_INFO */
#define TRSI_FIN 5   /* FTEXT dans l'arbre TRAN_INFO */
#define TRSI_SENS 6   /* BUTTON dans l'arbre TRAN_INFO */
#define TRSI_AFFSPLINE 7   /* BUTTON dans l'arbre TRAN_INFO */
#define TRSI_SPLINE 8   /* BOXTEXT dans l'arbre TRAN_INFO */

#define TRAN_PARA_DIAL 48  /* Formulaire/Dialogue */
#define TRSP_PT1 1   /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PF1 2   /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_MN1 3   /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_FON1 4   /* BOX dans l'arbre TRAN_PARA_DIAL */
#define TRSP_ASS1 5   /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PL1 6   /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PTS1 7   /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_TSPL1 8   /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_SIMG1 9   /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_IMG1 10  /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CT1 31  /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_C1  32  /* BOX dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CT2 33  /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_C2  34  /* BOX dans l'arbre TRAN_PARA_DIAL */
#define TRSP_SW1 35  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_SW2 36  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_SW3 37  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_SW4 38  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CDT1 39  /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CDX1 40  /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CDY1 41  /* TEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_CDC1 42  /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */
#define TRSP_TREEL 47  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_ANIM 48  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PREV 49  /* BOX dans l'arbre TRAN_PARA_DIAL */
#define TRSP_OK  50  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_ANN 51  /* BUTTON dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PREV_FON 52  /* BOX dans l'arbre TRAN_PARA_DIAL */
#define TRSP_PREV_ASS 53  /* BOXTEXT dans l'arbre TRAN_PARA_DIAL */

#define IMAGES   49  /* Formulaire/Dialogue */
#define IMG_TIME 1   /* IMAGE dans l'arbre IMAGES */
#define IMG_FL_HT 2   /* IMAGE dans l'arbre IMAGES */
#define IMG_FL_BAS 3   /* IMAGE dans l'arbre IMAGES */

#define CHX_EFFET 50  /* Formulaire/Dialogue */
#define CEFF_OK  1   /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_ANN 2   /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_AVFON 3   /* BOX dans l'arbre CHX_EFFET */
#define CEFF_AV1 4   /* TEXT dans l'arbre CHX_EFFET */
#define CEFF_UP  20  /* BOXCHAR dans l'arbre CHX_EFFET */
#define CEFF_FON 21  /* BOX dans l'arbre CHX_EFFET */
#define CEFF_ASS 22  /* BOXCHAR dans l'arbre CHX_EFFET */
#define CEFF_DOWN 23  /* BOXCHAR dans l'arbre CHX_EFFET */
#define CEFF_CURFON 26  /* BOX dans l'arbre CHX_EFFET */
#define CEFF_CU1 27  /* TEXT dans l'arbre CHX_EFFET */
#define CEFF_APP 43  /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_EFF 46  /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_LOAD 48  /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_SAVE 49  /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_PARAM 50  /* BUTTON dans l'arbre CHX_EFFET */
#define CEFF_MEM 51  /* BOXTEXT dans l'arbre CHX_EFFET */
#define CEFF_RAP 52  /* BOXTEXT dans l'arbre CHX_EFFET */

#define SUP_PIS  51  /* Formulaire/Dialogue */
#define SUPI_A   1   /* BUTTON dans l'arbre SUP_PIS */
#define SUPI_B   4   /* BUTTON dans l'arbre SUP_PIS */
#define SUPI_G   5   /* BUTTON dans l'arbre SUP_PIS */

#define BOOTING  52  /* Formulaire/Dialogue */
#define BOOT_TEXT 3   /* BOXTEXT dans l'arbre BOOTING */
#define BOOT_FON 4   /* BOX dans l'arbre BOOTING */
#define BOOT_ASS 5   /* BOX dans l'arbre BOOTING */

#define NOWIND   0   /* Chaine d'alerte */
